#!/usr/bin/perl
print("Starting pre-commit hook\n");
$filename = "dirty.pack.user.js";

#remove BOM
exec ("sed -i '1 s/^\xef\xbb\xbf//' dirty.pack.user.js");


open ( FILE, $filename) or die "Cannot open file: $!";

$found = 0;
while ( $line = <FILE> ) {
    if ($line =~ m/	buildtime:(.+)/) {
			$time = time();
			$found = 1;
			push(@outLines, "	buildtime: ".$time.",\r\n");
			print("Set buildtime to " . $time . ".\n");
		}else{
			push(@outLines, $line);
		}
}
close FILE;

if($found == 0){die "Buildtime marker not found in js file";}

open ( OUTFILE, ">$filename" );
print ( OUTFILE @outLines );
close ( OUTFILE );

exec ('git add dirty.pack.user.js');
